gpu_id: ""
seed: 10000
display: True
im_size: 64

diffusion:
  target: models.script_util.create_gaussian_diffusion
  params:
    steps: 1000
    learn_sigma: True
    sigma_small: False
    noise_schedule: linear
    use_kl: False
    predict_xstart: False
    rescale_timesteps: False
    rescale_learned_sigmas: True
    timestep_respacing: ""

model:
  target: models.unet.UNetModel
  ckpt_path: /home/sivark/supporting_files/denoising/trained_models/diffusion/ckpts_from_shivesh/ema0999_model_580000_planaria.pth
  params:
    image_size: 64
    in_channels: 1
    model_channels: 32
    out_channels: 2
    attention_resolutions: [32, 16, 8]
    dropout: 0
    channel_mult: [1, 2, 4, 8, 8, 16, 16]
    num_res_blocks: [1, 2, 2, 2, 2, 3, 4]
    conv_resample: True
    dims: 2
    use_fp16: False
    num_head_channels: 64
    use_scale_shift_norm: True
    resblock_updown: False
    use_new_attention_order: False

model_ir: ~
